# Generated by Django 4.2.11 on 2024-04-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('short_description', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='English', max_length=200)),
                ('thumbnail', models.ImageField(default='', upload_to='thumbnails/')),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category')),
                ('instructor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('video', models.FileField(upload_to='courses/')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
        ),
    ]
